### ISSUE TITLE
More robust color swatches

### ISSUE THREAD

**Issue by schweitzdesign** [forever-inc/forever-style-guide#19]
https://github.com/forever-inc/forever-style-guide/blob/96a9fe07f5d0158139d68b645ad1d6d12e6f05b4/app/assets/stylesheets/style_guide/modules/_color_swatch.scss

It would be nice to be able to use something akin to these for setting an element's background color like 
```
<div class="color_block color-blue">
Here are things on a blue background
</div>
```
or maybe better 

```
<div class="color_block-blue color-gray-100">
Here would be light gray text on a blue background
</div>
```

**Comment by nmcclay** [comment]
We actually do this already, the problem is specificity: https://github.com/forever-inc/forever-style-guide/blob/master/app/assets/stylesheets/forever_style_guide/globals/_colors.scss#L37

I'm a big fan of how materializecss handles this from a declarative css class perspective: http://materializecss.com/color.html

They split colors, color modifiers and effects into discreet classes that let you mix and match.

**Comment by schweitzdesign** [comment]
The materialize approach is interesting. It certainly gives you a much broader palette to draw from.

I was looking in the wrong place initially (swatches) and compared to our existing _colors.scss I was thinking we'd just extend that a touch further:

```
@each $id, $color in $colors {
  .color-#{$id} {
    color: #{$color};
  }
  .color_block-#{$id} {
    background-color: #{$color};
  }
}
```

Since right now we can declare the type color, but not the background color.
